FROM node:18.16.0-alpine as build

WORKDIR /app/frontend
COPY ./reactapp/package.json ./
COPY .reactapp/package-lock.json ./
RUN npm ci --silent
COPY ./reactapp/ ./
RUN  npm run build

FROM nginx:stable-plpine
COPY --from=build /app/frontend/build /usr/share/nginx/html
CMD [ "nginx", "-g", "deamon off;" ]